### ISSUE TITLE
Docker compose fail on build

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#44]
#### :tophat: User Story

As a developer, when I clone a clean copy and run 
`$ docker-compose build`

I get an error: 
```
Step 12 : RUN cd /tmp && bundle install
 ---> Running in 53a7badfc8bc
The path `/tmp/engines/decidim-debates` does not exist.
ERROR: Service 'app' failed to build: The command '/bin/sh -c cd /tmp && bundle install' returned a non-zero code: 13
```

I've the latest stable release (1.10) 
```
$ docker-compose --version
docker-compose version 1.10.0, build 4bd6f1a
```

#### :dart: Acceptance criteria

I should run `$ docker-compose build` without errors

**Comment by oriolgual** [comment]
Can you change your Dockerfile and add 

`ADD ./decidim-debates/ /tmp/decidim-debates/`

before bundle install ?

**Comment by oriolgual** [comment]
I've tried with this:

`
FROM ruby:2.4.0
MAINTAINER david.morcillo@codegram.com

ARG rails_env=production
ARG secret_key_base=

ENV APP_HOME /code
ENV RAILS_ENV $rails_env
ENV SECRET_KEY_BASE $secret_key_base

RUN apt-get update

RUN curl -sL https://deb.nodesource.com/setup_5.x | bash && \
    apt-get install -y nodejs locales
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Set the locale
RUN locale
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8
RUN dpkg-reconfigure locales

ADD Gemfile /tmp/Gemfile
ADD Gemfile.lock /tmp/Gemfile.lock
RUN mkdir -p /tmp/engines
ADD ./engines/decidim-debates /tmp/engines/decidim-debates
RUN cd /tmp && /bin/bash -c "bundle install"

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
ADD . $APP_HOME

RUN bundle exec rake DATABASE_URL=postgresql://user:pass@127.0.0.1/dbname assets:precompile

CMD ["bundle", "exec", "rails", "s", "-b0.0.0.0"]
`

But failed :( 

All the locales stuff is because `bundle install` won't run. Maybe @beagleknight can help.

**Comment by beagleknight** [comment]
I found a solution for the locales problem but I can't find the docker image right now. I will take a look soon!
